package com.huateng.haobai.ppcore.control;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-08-18T17:35:14.766+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "IDispatchControl",
                  wsdlLocation = "http://*/provfront/services/businessService?wsdl",
                  targetNamespace = "http://control.ppcore.haobai.huateng.com") 
public class IDispatchControl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://control.ppcore.haobai.huateng.com", "IDispatchControl");
    public final static QName IDispatchControlHttpPort = new QName("http://control.ppcore.haobai.huateng.com", "IDispatchControlHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://*/provfront/services/businessService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IDispatchControl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://*/provfront/services/businessService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IDispatchControl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IDispatchControl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDispatchControl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IDispatchControl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IDispatchControl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IDispatchControl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IDispatchControlPortType
     */
    @WebEndpoint(name = "IDispatchControlHttpPort")
    public IDispatchControlPortType getIDispatchControlHttpPort() {
        return super.getPort(IDispatchControlHttpPort, IDispatchControlPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDispatchControlPortType
     */
    @WebEndpoint(name = "IDispatchControlHttpPort")
    public IDispatchControlPortType getIDispatchControlHttpPort(WebServiceFeature... features) {
        return super.getPort(IDispatchControlHttpPort, IDispatchControlPortType.class, features);
    }

}
