
package com.huateng.haobai.ppcore.control;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-09-12T09:26:10.264+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class IDispatchControl1PortType_IDispatchControl1HttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://control.ppcore.haobai.huateng.com", "IDispatchControl1");

    private IDispatchControl1PortType_IDispatchControl1HttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IDispatchControl1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IDispatchControl1 ss = new IDispatchControl1(wsdlURL, SERVICE_NAME);
        IDispatchControl1PortType port = ss.getIDispatchControl1HttpPort();  
        
        {
        System.out.println("Invoking dispatchCommand...");
        java.lang.String _dispatchCommand_in0 = "1";
        java.lang.String _dispatchCommand_in1 = "<?xml version=\"1.0\" ?>\n" +
                "<ROWDATA>\n" +
                "\n" +
                "<ROW>\n" +
                "  <C0>1</C0>\n" +
                "  <RECORD_NO>61392</RECORD_NO>\n" +
                "  <ORG_CODE>113610000000000</ORG_CODE>\n" +
                "  <ORG_TYPE>1</ORG_TYPE>\n" +
                "  <SUB_TYPE>13</SUB_TYPE>\n" +
                "  <ORG_FNAME>&#38485;&#35199;&#33829;&#19994;&#21381;&#29616;&#37329;&#20805;&#20540;</ORG_FNAME>\n" +
                "  <ORG_SNAME>&#38485;&#35199;&#33829;&#19994;&#21381;&#29616;&#37329;&#20805;&#20540;</ORG_SNAME>\n" +
                "  <INDUSTRY_TYPE>4900</INDUSTRY_TYPE>\n" +
                "  <ADDRESS></ADDRESS>\n" +
                "  <ZIP_CODE></ZIP_CODE>\n" +
                "  <BUSINESS_LICENSE_NO></BUSINESS_LICENSE_NO>\n" +
                "  <ORGANIZATION_CODE>SETTLE_CENTER</ORGANIZATION_CODE>\n" +
                "  <LEGAL_REPRESENTIVE_NAME></LEGAL_REPRESENTIVE_NAME>\n" +
                "  <LINKMAN_NAME></LINKMAN_NAME>\n" +
                "  <LINKMAN_PHONE></LINKMAN_PHONE>\n" +
                "  <LINKMAN_FAX></LINKMAN_FAX>\n" +
                "  <LINKMAN_EMAIL></LINKMAN_EMAIL>\n" +
                "  <SERVICE_LEVEL>1</SERVICE_LEVEL>\n" +
                "  <RISK_LEVEL>1</RISK_LEVEL>\n" +
                "  <ALLOW_TXN>10S003,10S002,10S001,121B10,141B10,721021,261010,131101,131041,131040,121200,121111,121110,121101,121091,121080,121021,121020,121014,121011,103130,103120,103110,103100,103090,103080,103070,103060,103050,103040,103030,103020,103010,103001,103000,102140,102130,102120,102110,102100,102090,102080,102070,102060,102050,102040,102030,102011,102010,102000,101150,101140,101134,101133,101132,101131,101130,101120,101110,101100,101090,101080,101070,101060,101050,101040,101030,101020,101012,101011,101010,101001,101000,100150,100120,100110,100100,100090,100080,100070,100060,100050,100040,100030,100020,100010,133000,133001,133002,133003,263010,131280,131281,131282,131283,761010,131010,131100,</ALLOW_TXN>\n" +
                "  <STATUS>1</STATUS>\n" +
                "  <AREA_CODE>610000</AREA_CODE>\n" +
                "  <CITY_CODE></CITY_CODE>\n" +
                "  <UP_ORG_CODE></UP_ORG_CODE>\n" +
                "  <SIGN_ORG_CODE>002610000000000</SIGN_ORG_CODE>\n" +
                "  <CLEAR_ORG_CODE></CLEAR_ORG_CODE>\n" +
                "  <SETTLE_ORG_CODE>113610000000000</SETTLE_ORG_CODE>\n" +
                "  <SETTLE_MODE>2</SETTLE_MODE>\n" +
                "  <REAL_MODE>1</REAL_MODE>\n" +
                "  <CLEAR_DATE></CLEAR_DATE>\n" +
                "  <SETTLE_DATE></SETTLE_DATE>\n" +
                "  <F_LINKMAN_NAME></F_LINKMAN_NAME>\n" +
                "  <F_LINKMAN_PHONE></F_LINKMAN_PHONE>\n" +
                "  <F_LINKMAN_FAX></F_LINKMAN_FAX>\n" +
                "  <F_LINKMAN_EMAIL></F_LINKMAN_EMAIL>\n" +
                "  <CREATE_UID>0000000000002749</CREATE_UID>\n" +
                "  <CREATE_TIME>15-6&#26376; -13 03.34.03.407000 &#19979;&#21320;</CREATE_TIME>\n" +
                "  <CHECK_FLAG>2</CHECK_FLAG>\n" +
                "  <CHECK_UID>0000000000011334</CHECK_UID>\n" +
                "  <CHECK_TIME>28-5&#26376; -14 07.36.51.417000 &#19979;&#21320;</CHECK_TIME>\n" +
                "  <LAST_MODIFY_UID>0000000000011994</LAST_MODIFY_UID>\n" +
                "  <LAST_MODIFY_TIME>28-5&#26376; -14 07.33.09.372000 &#19979;&#21320;</LAST_MODIFY_TIME>\n" +
                "  <SETTAMT_MIN1></SETTAMT_MIN1>\n" +
                "  <SETTAMT_MIN2></SETTAMT_MIN2>\n" +
                "  <SETTAMT_MIN3></SETTAMT_MIN3>\n" +
                "  <SETTAMT_MIN4></SETTAMT_MIN4>\n" +
                "  <SETTAMT_MIN5></SETTAMT_MIN5>\n" +
                "  <CHARGE_ACC_FLAG>0</CHARGE_ACC_FLAG>\n" +
                "  <ORG_KIND></ORG_KIND>\n" +
                "  <ARCHIVE_TIME></ARCHIVE_TIME>\n" +
                "  <ARCHIVED_FLAG>1</ARCHIVED_FLAG>\n" +
                "  <L_RECORD_NO>61392</L_RECORD_NO>\n" +
                "  <REMARK></REMARK>\n" +
                "  <POSP_FLAG></POSP_FLAG>\n" +
                "  <PAY_TYPE></PAY_TYPE>\n" +
                "  <RESV_FLD1></RESV_FLD1>\n" +
                "  <RESV_FLD2>2</RESV_FLD2>\n" +
                "  <RESV_FLD3>0160914DBA&#28155;&#21152;&#28040;&#20914;&#27491;&#26435;&#38480;</RESV_FLD3>\n" +
                "  <LEGAL_PERSON_ID></LEGAL_PERSON_ID>\n" +
                "</ROW>\n" +
                "\n" +
                "</ROWDATA>";
        java.lang.String _dispatchCommand__return = port.dispatchCommand(_dispatchCommand_in0, _dispatchCommand_in1);
        System.out.println("dispatchCommand.result=" + _dispatchCommand__return);


        }

        System.exit(0);
    }

}
