package com.huateng.haobai.ppcore.control;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-09-12T09:26:10.310+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "IDispatchControl1", 
                  wsdlLocation = "http://116.228.151.50:7000/mobileterminalfront/services/businessService3?wsdl",
                  targetNamespace = "http://control.ppcore.haobai.huateng.com") 
public class IDispatchControl1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://control.ppcore.haobai.huateng.com", "IDispatchControl1");
    public final static QName IDispatchControl1HttpPort = new QName("http://control.ppcore.haobai.huateng.com", "IDispatchControl1HttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://116.228.151.50:7000/mobileterminalfront/services/businessService3?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IDispatchControl1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://116.228.151.50:7000/mobileterminalfront/services/businessService3?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IDispatchControl1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IDispatchControl1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDispatchControl1() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IDispatchControl1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IDispatchControl1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IDispatchControl1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IDispatchControl1PortType
     */
    @WebEndpoint(name = "IDispatchControl1HttpPort")
    public IDispatchControl1PortType getIDispatchControl1HttpPort() {
        return super.getPort(IDispatchControl1HttpPort, IDispatchControl1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDispatchControl1PortType
     */
    @WebEndpoint(name = "IDispatchControl1HttpPort")
    public IDispatchControl1PortType getIDispatchControl1HttpPort(WebServiceFeature... features) {
        return super.getPort(IDispatchControl1HttpPort, IDispatchControl1PortType.class, features);
    }

}
